spring.application.name=weather-system-maven

spring.datasource.url=jdbc:postgresql://localhost:5432/weather_order_db
spring.datasource.username=postgres
spring.datasource.password=SLON123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

weather.api.geocoding-base-url=https://geocoding-api.open-meteo.com
weather.api.forecast-base-url=https://api.open-meteo.com